# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  default_branch: master
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false

labels:
  - name: 'automerge'
    color: '#ededed'

  - name: 'bc break'
    color: '#ff0000'

  - name: 'bugfix'
    color: '#fc2929'

  - name: 'docs'
    color: '#fbca04'

  - name: 'feature'
    color: '#0e8a16'

  - name: 'dependency'
    color: '#5fb2d8'

  - name: 'help wanted'
    color: '#159818'

  - name: 'invalid'
    color: '#e6e6e6'

  - name: 'pedantic'
    color: '#DDDDDD'

  - name: 'question'
    color: '#cc317c'

branches:
  - name: master
    protection:
      enforce_admins: false
      required_status_checks:
        contexts:
          - "Coding Standards (7.4)"
          - "Static Code Analysis (7.4)"
          - "Tests (7.2, lowest)"
          - "Tests (7.2, highest)"
          - "Tests (7.3, lowest)"
          - "Tests (7.3, highest)"
          - "Tests (7.4, lowest)"
          - "Tests (7.4, highest)"
          - "Code Coverage (7.4)"
        strict: true

      required_pull_request_reviews: null
      restrictions: null
