_extends: .github

repository:
  name: NucleosSetlistFmBundle
  description: 🔌 This bundle provides services for using the setlist.fm API with symfony.
  homepage: https://nucleos.rocks
  topics: hacktoberfest, symfony, symfony-bundle, bundle, php, setlistfm, setlist, api, webservice-client
